language: php
php:
  - 7.4
  - 8.0

sudo: false

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpcs --standard=psr2 src/
  - php vendor/bin/phpunit --coverage-clover=./build/logs/coverage.clover

after_script:
  - |
    if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover ./build/logs/coverage.clover;
    fi
